### ISSUE TITLE
Expand not working properly

### ISSUE THREAD

**Issue by sjeon87** [proj3rd/lib3rd#35]
```
            item.expand(asn1Pool, _this.getModuleNameToPass(moduleName));
                 ^

TypeError: item.expand is not a function
    at C:\Users\songsong\3gpp\dist\asn1\classes\sequence.js:36:18
    at Array.forEach (<anonymous>)
    at Sequence.expand (C:\Users\songsong\3gpp\dist\asn1\classes\sequence.js:35:20)
    at Object.expand (C:\Users\songsong\3gpp\dist\asn1\expand.js:6:27)
    at C:\Users\songsong\3gpp\dist\asn1\format\index.js:74:33
    at Array.map (<anonymous>)
    at C:\Users\songsong\3gpp\dist\asn1\format\index.js:73:41
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

**Comment by sjeon87** [comment]
fb81100bb75ccae0d9be8e3f07d15c0d7266c4d3
