### ISSUE TITLE
constants of undefined

### ISSUE THREAD

**Issue by sjeon87** [proj3rd/lib3rd#38]
```
    if (refName in asn1Pool[moduleName][key]) {
                                       ^

TypeError: Cannot read property 'constants' of undefined
    at findReference (C:\Users\songsong\3gpp\dist\asn1\utils.js:30:40)
    at Object.findConstantValue (C:\Users\songsong\3gpp\dist\asn1\utils.js:20:12)
    at C:\Users\songsong\3gpp\dist\asn1\format\xlsx.js:147:39
    at Array.forEach (<anonymous>)
    at fillConstants (C:\Users\songsong\3gpp\dist\asn1\format\xlsx.js:145:41)
    at C:\Users\songsong\3gpp\dist\asn1\format\xlsx.js:63:18
    at Array.forEach (<anonymous>)
    at Object.format (C:\Users\songsong\3gpp\dist\asn1\format\xlsx.js:45:12)
    at C:\Users\songsong\3gpp\dist\asn1\format\index.js:87:43
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

**Comment by sjeon87** [comment]
#41
