### ISSUE TITLE
Maximum call stack size exceeded when expand

### ISSUE THREAD

**Issue by sjeon87** [proj3rd/lib3rd#39]
```
C:\Users\songsong\3gpp\node_modules\lodash\lodash.js:1198
      return func(transform(arg));
                  ^

RangeError: Maximum call stack size exceeded
    at Object (<anonymous>)
    at C:\Users\songsong\3gpp\node_modules\lodash\lodash.js:1198:19
    at baseKeys (C:\Users\songsong\3gpp\node_modules\lodash\lodash.js:3484:16)
    at keys (C:\Users\songsong\3gpp\node_modules\lodash\lodash.js:13307:60)
    at baseGetAllKeys (C:\Users\songsong\3gpp\node_modules\lodash\lodash.js:3052:20)
    at getAllKeys (C:\Users\songsong\3gpp\node_modules\lodash\lodash.js:5852:14)
    at baseClone (C:\Users\songsong\3gpp\node_modules\lodash\lodash.js:2684:39)
    at Function.cloneDeep (C:\Users\songsong\3gpp\node_modules\lodash\lodash.js:11088:14)
    at DefinedType.expand (C:\Users\songsong\3gpp\dist\asn1\classes\definedType.js:43:35)
    at DefinedType.expand (C:\Users\songsong\3gpp\dist\asn1\classes\definedType.js:63:20)
```

**Comment by sjeon87** [comment]
Reproduce:

```sh
node dist\asn1\format 36331-f51.asn1 MeasConfig --expand --format=xlsx
node dist\asn1\format 36331-f51.asn1 MeasConfig --expand --format=text
```

**Comment by gsongsong** [comment]
- [ ] Expand
- [ ] Format to text
- [ ] Format to excel

**Comment by sjeon87** [comment]
e93132e525a8367ba7b75279a1260a0d2730d3a4
